name: 'Quinn Chaffee'
description: 'Download and persist a Task Definition json file'
author: 'Sportshub Technologies LLC'
inputs:
  aws-region:
    description: 'AWS Region'
    required: true
  aws-profile:
    description: 'aws-profile'
    required: true
  aws-cluster-name:
    description: 'aws-cluster-name'
    required: true
  aws-service-name:
    description: 'aws-service-name'
    required: true
  docker-image:
    description: 'docker-image'
    required: true
  docker-build-number:
    description: 'docker-build-number'
    required: true
  app-env:
    description: 'app-env'
    required: true
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
  container-definition-names:
    description: 'Comma separated list of the container definition names in the task definition'
runs:
  using: 'node12'
  main: 'dist/index.js'